import { format } from 'date-fns';
import { es } from 'date-fns/locale';
import type { ProgramMachineType } from '@/lib/types/index';

const AUTO_NAME_RE = /^\d{1,2}\s+[A-ZÁÉÍÓÚÑÜ]{3}\s+x\d+\s+y?(C|G|XL|ABC)$/i;

function toDate(date: Date | string): Date | null {
  if (date instanceof Date) return Number.isNaN(date.getTime()) ? null : date;
  const part = date.split('T')[0] || '';
  const [y, m, d] = part.split('-').map(Number);
  if (!y || !m || !d) return null;
  return new Date(y, m - 1, d);
}

export function generateProgramName(opts: {
  date: Date | string;
  machine: ProgramMachineType;
  stampCount: number;
}): string {
  const date = toDate(opts.date);
  if (!date || !opts.machine) return '';
  const day = format(date, 'd', { locale: es });
  const month = format(date, 'MMM', { locale: es }).toUpperCase();
  const machineLabel = opts.machine === 'XL' ? 'XL' : opts.machine;
  return `${day} ${month} x${opts.stampCount} ${machineLabel}`;
}

export function isAutoGeneratedProgramName(name: string | null | undefined): boolean {
  if (!name) return false;
  return AUTO_NAME_RE.test(name.trim());
}

/** Si el nombre actual es auto-generado, devuelve el nombre con el nuevo conteo. Si fue editado a mano, null. */
export function nextAutoProgramName(
  currentName: string | null | undefined,
  opts: { date: Date | string; machine: ProgramMachineType; stampCount: number },
): string | null {
  if (!isAutoGeneratedProgramName(currentName)) return null;
  return generateProgramName(opts);
}
