import { describe, expect, it } from 'vitest';
import { generateProgramName, isAutoGeneratedProgramName, nextAutoProgramName } from './programName';

describe('generateProgramName', () => {
  it('arma el nombre con día, mes, cantidad y máquina, sin "y"', () => {
    expect(generateProgramName({
      date: new Date(2026, 8, 6),
      machine: 'C',
      stampCount: 1,
    })).toBe('6 SEP x1 C');
  });

  it('usa XL como etiqueta de máquina', () => {
    expect(generateProgramName({
      date: '2026-01-15',
      machine: 'XL',
      stampCount: 12,
    })).toBe('15 ENE x12 XL');
  });
});

describe('isAutoGeneratedProgramName', () => {
  it('acepta el formato nuevo y el viejo con y', () => {
    expect(isAutoGeneratedProgramName('6 SEP x1 C')).toBe(true);
    expect(isAutoGeneratedProgramName('6 SEP x1 yC')).toBe(true);
    expect(isAutoGeneratedProgramName('Programa de Juli')).toBe(false);
  });
});

describe('nextAutoProgramName', () => {
  it('actualiza el conteo si el nombre es auto-generado', () => {
    expect(nextAutoProgramName('6 SEP x1 C', {
      date: new Date(2026, 8, 6),
      machine: 'C',
      stampCount: 3,
    })).toBe('6 SEP x3 C');
  });

  it('no toca un nombre editado a mano', () => {
    expect(nextAutoProgramName('Tanda especial', {
      date: new Date(2026, 8, 6),
      machine: 'C',
      stampCount: 3,
    })).toBeNull();
  });
});
